function menuText() {
  return [
    '🤖 BOT KEUANGAN KEGIATAN',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '👤 USER',
    '━━━━━━━━━━━━━━━━━━',
    '📋 listpeserta',
    'Melihat daftar peserta',
    '',
    '📒 riwayat',
    'Melihat riwayat transaksi',
    '',
    '🧮 Kalkulator',
    'tambah 10 5',
    'kurang 10 5',
    'kali 10 5',
    'bagi 10 5',
    '',
    '🌤 weather',
    'Melihat info cuaca',
    '',
    '📝 todolist',
    'Melihat daftar tugas',
    '',
    '⚡ keyword command',
    'Menjalankan command otomatis yang tersedia',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '👑 ADMIN GROUP',
    '━━━━━━━━━━━━━━━━━━',
    '💰 TRANSAKSI',
    '+ nominal (catatan)  → Menambah pemasukan',
    '- nominal (catatan)  → Menambah pengeluaran',
    '',
    '📒 RIWAYAT',
    'riwayat',
    'riwayat 50',
    'riwayat hari ini',
    'riwayat 2026-02-18',
    'riwayat 2026-02-01 2026-02-18',
    '',
    '➕ addpeserta',
    '✏️ updatepeserta',
    '❌ delpeserta',
    '📌 command',
    '🗑 delcommand',
    '📄 listcommand',
    '⚙ setheader',
    '⏰ remind',
    '📋 listremind',
    '❌ noremind',
    '📝 todo tambah',
    '✅ doto',
    '🧹 clearall',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '🔑 OWNER BOT',
    '━━━━━━━━━━━━━━━━━━',
    '#infogroup',
    '#aktif',
    '#nonaktif',
    '#statussewa',
<<<<<<< HEAD
    '',
    '*Klaim Owner Cepat:*',
    '#claimowner'
=======
    '#broadcast',
    '#health'
>>>>>>> d05a084129667fa872368bd0419fe51dc276fe58
  ].join('\n');
}

module.exports = { menuText };
