function menuText() {
  return [
    '🤖 *BOT KEUANGAN KEGIATAN* 🤖',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '👤 *USER* 👤',
    '━━━━━━━━━━━━━━━━━━',
    '📋 listpeserta',
    '📒 riwayat',
    '🧮 kalkulator (tambah, kurang, kali, bagi)',
    '🌤 weather',
    '📝 todolist',
    '⚡ keyword command',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '👑 *ADMIN GROUP* 👑',
    '━━━━━━━━━━━━━━━━━━',
    '💰 + nominal (catatan)',
    '💸 - nominal (catatan)',
    '',
    '✏️ edit no (format baru)',
    '❌ hapus no',
    '🔍 detail no',
    '',
    '➕ addpeserta',
    '✏️ updatepeserta',
    '❌ delpeserta',
    '',
    '📌 command KEYWORD@(text)',
    '🔄 updatecommand KEYWORD@(text)',
    '🗑 delcommand',
    '📄 listcommand',
    '',
    '⚙ setheader@(text)',
    '⚙ typo (on/off)',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '⏰ *REMINDER* ⏰',
    '━━━━━━━━━━━━━━━━━━',
    '🔔 remind (time/date)@(text)',
    '📜 listremind',
    '🔕 noremind (time/date)',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '📝 *TO DO* 📝',
    '━━━━━━━━━━━━━━━━━━',
    '➕ todo (text)',
    '📋 todolist',
    '✅ doto (no)',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '🔑 *OWNER* 🔑',
    '━━━━━━━━━━━━━━━━━━',
    'ℹ️ #infogroup',
    '✅ #aktif (idgrup) (hari)',
    '⛔ #nonaktif (idgrup)',
    '📊 #statussewa',
    '📢 #broadcast@(pesan)',
    '📢 brdcs 62xxx,62xxx@(pesan)',
    '🩺 #health'
  ].join('\n');
}

module.exports = { menuText };
