function menuText() {
  return [
    '🤖 MENU BOT KEUANGAN KEGIATAN',
    '',
    '*Input Transaksi (butuh sewa aktif):*',
    '+ 15000 (Donasi Pak RT)',
    '- 12000 (Beli air mineral)',
    '',
    '*Keuangan:*',
    'riwayat | riwayat 50 | riwayat hari ini',
    'riwayat 2026-02-18 | riwayat 2026-02-01 2026-02-18',
    'edit 2 - 10000 (Revisi beli air)',
    'hapus 3 | detail 1',
    'saldo | saldo hari ini | saldo bulan ini',
    '',
    '*Peserta Opentrip:*',
    'listpeserta | listpeserta 2',
    'ketik angka (contoh: 4) untuk detail peserta dari list terakhir',
    'addpeserta Nama@(Data diri)',
    'updatepeserta no 4@(Data baru)',
    'delpeserta no 4',
    '',
    '*Custom Command:*',
    'command KEYWORD@Output',
    'listcommand | detailcommand KEYWORD | delcommand KEYWORD',
    '',
    '*Kalkulator:*',
    'tambah 100 50 | kurang 100 20 | kali 10 5 | bagi 10 4',
    '',
    '*Owner command (#):*',
    '#infogroup [idgrup]',
    '#aktif idgrup hari',
    '#nonaktif idgrup',
    '#statussewa',
    '',
    '*Klaim Owner Cepat:*',
    '#claimowner'
  ].join('\n');
}

module.exports = { menuText };
